version conflicts
webmaxru/pwa-workshop pull request #1
Opened 2017-04-28 16:20 UTC by web-dave

App-shell seems to generate a totally version conflict. Can't solve it. And angular material needs animation module

2017-04-28 16:22 UTC, web-dave commented
I think appshell and material are in beta very much.

2017-04-29 09:08 UTC, webmaxru commented on .gitignore
> +/build
I commit `build` folder by intention - this `pwa-workshop` is for "generic" JavaScript workshops (unlike `pwa-workshop-angular`), without need to have `angular-cli` installed.

2017-04-29 09:10 UTC, webmaxru commented on package.json
> +    "rest": "cd ../pwa-workshop-api && npm start"
I'd prefer to not to bind these two repos so tight

2017-04-29 09:11 UTC, webmaxru requested changes
Thanks for contributing! Please have a look at my comments.

2017-04-29 09:36 UTC, web-dave commented on .gitignore
> +/build
That makes totally sense. I'll fix it today.

2017-04-29 09:37 UTC, web-dave commented on package.json
> +    "rest": "cd ../pwa-workshop-api && npm start"
Ok. I love this way but I'm fine with it. I'll fix it Today

2017-04-29 15:02 UTC, web-dave commented
I did the changes as requested.

2017-04-30 07:15 UTC, merged

2017-04-30 07:18 UTC, web-dave commented
I'm very excited about the workshop I'll do on Friday.